title: Web Machine Learning
email: anssi.kostiainen
description: >
  Making Machine Learning a first-class web citizen
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: webmachinelearning
github_username:  webmachinelearning
logo: https://avatars2.githubusercontent.com/u/42399997

google_analytics: G-6TK7JD3KKY

theme: minima
plugins:
  - jekyll-feed
  - jekyll-toc
excerpt_separator: <!-- more -->
    
host: 0.0.0.0

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
